### ISSUE TITLE
Can I log doctrine queries with the slim logger ?

### ISSUE THREAD

**Issue by borgogelli** [juliangut/slim-doctrine#1]
Can I log doctrine queries with the slim logger ?

**Comment by juliangut** [comment]
Hi,

first of all I have to tell you Slim3 doesn't bundle a logger as Slim2 did, so for Slim3 you are responsible of registering your own logger. [PSR3](http://www.php-fig.org/psr/psr-3/) please

Once that's said, Doctrine indeed have a logging interface so that you can hook to doctrine in order to log every query execution.

In [Doctrine documentation](http://doctrine-orm.readthedocs.org/en/latest/reference/advanced-configuration.html#sql-logger-optional) you can see your logger should implement `Doctrine\DBAL\Logging\SQLLogger` with this signature

``` php
interface SQLLogger
{
    public function startQuery($sql, array $params = null, array $types = null);
    public function stopQuery();
}
```

Slim-doctrine doesn't allow you to set an SQL logger at this time. I see this can be added to the `EntityManagerBuilder`, feel free to PR or I'll do it as soon as I find time to

**Comment by juliangut** [comment]
I've just implemented the `sql_logger` option for configuring Doctrine SQL logger. As I commented above the only thing to do is use a logger implementing `\Doctrine\DBAL\Logging\SQLLogger`
